# Generated by Django 2.1.1 on 2018-09-26 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.CharField(default='SOME STRING', max_length=255)),
                ('obs_type', models.CharField(choices=[('tree', 'Tree'), ('bird', 'Bird'), ('flower', 'Flower'), ('buterfly', 'Butterfly')], default='none', max_length=255)),
                ('date', models.DateField(verbose_name='Date')),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Species', verbose_name='Species'),
        ),
    ]
