# Generated by Django 2.1.1 on 2018-09-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='photo',
            field=models.ImageField(default='no image', upload_to='media'),
        ),
    ]
