# Generated by Django 2.2.5 on 2020-04-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='photo',
            field=models.ImageField(default='no image', upload_to='images'),
        ),
    ]
