# Generated by Django 2.2.5 on 2020-04-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200403_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='photo',
            field=models.ImageField(default='no image', upload_to='media'),
        ),
    ]
