# Generated by Django 2.2.5 on 2020-04-20 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200403_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='species',
            name='obs_type',
            field=models.CharField(choices=[('tree', 'Tree'), ('bird', 'Bird'), ('flower', 'Flower'), ('butterfly', 'Butterfly')], default='none', max_length=255),
        ),
    ]
