# Generated by Django 2.2.5 on 2020-05-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200420_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='Flagtime',
            field=models.BooleanField(default=False),
        ),
    ]
