# Generated by Django 2.2.5 on 2020-05-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_observation_flagtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='Flagimage',
            field=models.BooleanField(default=False),
        ),
    ]
