# Generated by Django 2.2.5 on 2021-08-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200612_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='FlagLocation',
            field=models.BooleanField(default=False),
        ),
    ]
